name: coodyproj
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.14.0+5
  shared_preferences: ^0.5.3+4
  flutter_signin_button: ^0.2.8
  google_sign_in: ^4.0.7
  flutter_facebook_login: ^3.0.0
  cloud_firestore: ^0.13.7
  rxdart: ^0.24.1
  carousel_slider: ^1.3.0
  flutter_staggered_grid_view: ^0.3.0
  giffy_dialog: ^1.8.0
  animated_text_kit: ^2.2.0
  multiselect_formfield: ^0.1.4
  list_tile_switch: ^0.0.2
  flutter_html: ^1.0.2
  opencv_histogram_equality: ^0.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    -  assets/favorite_Analysis_page/illustration_FApage.png
    -  assets/icons/cart.png
    -  assets/icons/cart_blue.png
    -  assets/icons/menu.png
    -  assets/icons/minus.png
    -  assets/icons/filter.png
    -  assets/icons/bar.png
    -  assets/icons/active_filter.png
    -  assets/icons/fast-delivery.png
    -  assets/icons/free-shipping.png
    -  assets/icons/medal.png
    -  assets/icons/cart2.png
    -  assets/icons/bag.png
    -  assets/icons/
    -  assets/logo/blue.png
    -  assets/logo/blacklogo.png
    -  assets/star/star1.png
    -  assets/star/star11.png
    -  assets/star/starhalf.png
    -  assets/images/


  fonts:
    - family: Kopup
      fonts:
        - asset: assets/fonts/KoPubDotumLight.ttf
          weight: 300
        - asset: assets/fonts/KoPubDotumMedium.ttf
        - asset: assets/fonts/KoPubDotumBold.ttf
          weight: 700

    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-SemiBold.ttf
        - asset: assets/fonts/Archivo-SemiBoldItalic.ttf
