name: coodyproj
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_auth: ^0.14.0+5
  shared_preferences: ^0.5.3+4
  flutter_signin_button: ^0.2.8
  google_sign_in: ^4.0.7
  flutter_facebook_login: ^3.0.0
  cloud_firestore: ^0.13.7
  rxdart: ^0.24.1
  carousel_slider: ^1.3.0
  flutter_staggered_grid_view: ^0.3.2
  giffy_dialog: ^1.8.0
  animated_text_kit: ^2.2.0
  multiselect_formfield: ^0.1.4
  list_tile_switch: ^0.0.2
  flutter_html: ^1.0.2
  transparent_image: ^1.0.0
  flutter_email_sender: ^3.0.1
  html: ^0.14.0+4
  url_launcher: ^5.4.0
  iamport_flutter: ^0.9.13
  kopo: ^0.1.1
  flutter_rating_bar: ^3.2.0+1
  multi_image_picker: ^4.7.14
  permission_handler: ^3.1.0
  firebase_storage: ^3.1.6
  path_provider: ^1.6.24
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    -  assets/favorite_Analysis_page/illustration_FApage.png
    -  assets/icons/
    -  assets/icons/painter.png
    -  assets/icons/refresh.png
    -  assets/icons/tag.png
    -  assets/icons/cd.png
    -  assets/icons/hanger.png
    -  assets/icons/truck.png
    -  assets/icons/list.png
    -  assets/icons/box.png
    -  assets/icons/cart.png
    -  assets/icons/cart_blue.png
    -  assets/icons/menu.png
    -  assets/icons/minus.png
    -  assets/icons/filter.png
    -  assets/icons/Wfilter.png
    -  assets/icons/bar.png
    -  assets/icons/active_filter.png
    -  assets/icons/fast-delivery.png
    -  assets/icons/free-shipping.png
    -  assets/icons/medal.png
    -  assets/icons/cart2.png
    -  assets/icons/bag.png
    -  assets/icons/chart.png
    -  assets/icons/3d.png
    -  assets/icons/coin2.png
    -  assets/icons/discount.png
    -  assets/icons/giphy.gif
    -  assets/logo/4444.png
    -  assets/logo/P21.png
    -  assets/logo/WP21.png
    -  assets/logo/whitehor.png
    -  assets/star/star1.png
    -  assets/star/star11.png
    -  assets/star/starhalf.png
    -  assets/images/suc.png
    -  assets/images/DNA.gif
    -  assets/images/activity.png
    -  assets/images/romance.png
    -  assets/images/cube.gif
    -  assets/images/thisYearColor.png
    -  assets/images/fal.png
    -  assets/images/19.png
    -  assets/images/live.png
    -  assets/images/19.png
    -  assets/images/loading.png
    -  assets/splash/loading.gif
    -  assets/splash/Rolling.gif


  fonts:
    - family: Kopup
      fonts:
        - asset: assets/fonts/KoPubDotumLight.ttf
          weight: 300
        - asset: assets/fonts/KoPubDotumMedium.ttf
        - asset: assets/fonts/KoPubDotumBold.ttf
          weight: 700

    - family: metropolis
      fonts:
        - asset: assets/fonts/metropolis.bold.otf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf